export const PRESET_ICONS = [
    'Link2',
    'Globe',
    'Home',
    'Search',
    'Bell',
    'Star',
    'Bookmark',
    'Shield',
    'Briefcase',
    'Building',
    'Users',
    'User',
    'Settings',
    'FileText',
    'Folder',
    'ClipboardList',
    'DollarSign',
    'CreditCard',
    'Wallet',
    'ShoppingCart',
    'Receipt',
    'TrendingUp',
    'Image',
    'Video',
    'Music',
    'Camera',
    'Headphones',
    'Mic',
    'Play',
    'Code',
    'Terminal',
    'Database',
    'Cloud',
    'Server',
    'Cpu',
    'Wifi',
    'Monitor',
    'Mail',
    'MessageSquare',
    'Phone',
    'Send',
    'Share2',
    'Calendar',
    'Clock',
    'CalendarCheck',
    'Timer',
    'PieChart',
    'BarChart3',
    'LineChart',
    'Activity',
    'Zap',
    'Car',
    'Truck',
    'Bus',
    'Bike',
    'Plane',
    'Ship',
    'TrainFront',
    'Heart',
    'Stethoscope',
    'GraduationCap',
    'BookOpen',
    'Coffee',
    'Utensils',
    'Wrench',
    'Leaf',
    'Dumbbell',
    'Gamepad2',
    'Tv',
    'Compass',
    'Fingerprint',
    'Scan',
    'QrCode',
    'Key',
    'Lock',
    'BadgeCheck',
    'Clipboard',
    'Printer',
    'Store',
    'Factory',
];

export const PRESET_COLORS = [
    { name: 'Blue-Cyan', value: 'from-blue-500 to-cyan-500' },
    { name: 'Blue-Indigo', value: 'from-blue-600 to-indigo-700' },
    { name: 'Sky-Indigo', value: 'from-sky-500 to-indigo-600' },
    { name: 'Indigo-Purple', value: 'from-indigo-500 to-purple-700' },
    { name: 'Indigo-Blue', value: 'from-indigo-500 to-blue-600' },
    { name: 'Violet-Pink', value: 'from-violet-500 to-pink-600' },
    { name: 'Violet-Indigo', value: 'from-violet-500 to-indigo-600' },
    { name: 'Fuchsia-Pink', value: 'from-fuchsia-500 to-pink-700' },
    { name: 'Fuchsia-Violet', value: 'from-fuchsia-500 to-violet-600' },
    { name: 'Purple-Fuchsia', value: 'from-purple-500 to-fuchsia-600' },
    { name: 'Purple-Pink', value: 'from-purple-500 to-pink-500' },
    { name: 'Pink-Rose', value: 'from-pink-500 to-rose-600' },
    { name: 'Pink-Sky', value: 'from-pink-500 to-sky-500' },
    { name: 'Rose-Red', value: 'from-rose-500 to-red-600' },
    { name: 'Rose-Fuchsia', value: 'from-rose-500 to-fuchsia-500' },
    { name: 'Rose-Indigo', value: 'from-rose-500 to-indigo-700' },
    { name: 'Red-Orange', value: 'from-red-500 to-orange-500' },
    { name: 'Red-Pink', value: 'from-red-500 to-pink-600' },
    { name: 'Orange-Amber', value: 'from-orange-500 to-amber-600' },
    { name: 'Orange-Red', value: 'from-orange-500 to-red-600' },
    { name: 'Orange-Rose', value: 'from-orange-500 to-rose-500' },
    { name: 'Amber-Orange', value: 'from-amber-500 to-orange-600' },
    { name: 'Yellow-Orange', value: 'from-yellow-500 to-orange-500' },
    { name: 'Yellow-Lime', value: 'from-yellow-500 to-lime-500' },
    { name: 'Lime-Green', value: 'from-lime-500 to-green-600' },
    { name: 'Green-Emerald', value: 'from-green-500 to-emerald-600' },
    { name: 'Green-Lime', value: 'from-green-500 to-lime-500' },
    { name: 'Emerald-Teal', value: 'from-emerald-500 to-teal-600' },
    { name: 'Emerald-Cyan', value: 'from-emerald-500 to-cyan-500' },
    { name: 'Emerald-Purple', value: 'from-emerald-500 to-purple-700' },
    { name: 'Teal-Cyan', value: 'from-teal-500 to-cyan-600' },
    { name: 'Teal-Blue', value: 'from-teal-500 to-blue-500' },
    { name: 'Teal-Red', value: 'from-teal-500 to-rose-600' },
    { name: 'Cyan-Indigo', value: 'from-cyan-500 to-indigo-600' },
    { name: 'Cyan-Pink', value: 'from-cyan-500 to-pink-600' },
    { name: 'Sky-Purple', value: 'from-sky-500 to-violet-600' },
    { name: 'Slate-Gray', value: 'from-slate-600 to-gray-700' },
    { name: 'Slate-Orange', value: 'from-slate-600 to-orange-500' },
    { name: 'Zinc-Neutral', value: 'from-zinc-600 to-neutral-800' },
    { name: 'Zinc-Cyan', value: 'from-zinc-700 to-cyan-500' },
    { name: 'Gray-Stone', value: 'from-gray-600 to-stone-700' },
    { name: 'Gray-Orange', value: 'from-gray-800 to-orange-500' },
    { name: 'Stone-Orange', value: 'from-stone-600 to-orange-500' },
    { name: 'Amber-Purple', value: 'from-amber-500 to-purple-700' },
    { name: 'Blue-Yellow', value: 'from-blue-500 to-yellow-500' },
    { name: 'Green-Red', value: 'from-green-500 to-rose-500' },
    { name: 'Purple-Yellow', value: 'from-purple-600 to-yellow-500' },
    { name: 'Indigo-Green', value: 'from-indigo-500 to-green-500' },
];
